---
title: "Individual paper 1"
date: 2024-01-23
---

Research the agency where you work to find answers to each item listed below. Do not copy text or graphics from a website or other online platform; use your own words for each answer. In a 300-600 word typewritten paper, respond to the following (one-half point per full response to each):

-   The name of the agency and its principal address. If you work at a location other than the principal address, please indicate that location.

-   The names and titles of each of the agency’s governing board officials.

-   The names and titles of the agency’s chief administrative officer, and each department head who is a direct report to the chief administrative officer.

-   The total number of full-time and part-time employees in the agency.

-   The agency’s current total expenditure budget amount for the year, in all funds, and indicate whether fiscal-year (with FY end date) or calendar year.

-   The name and title of the chief Freedom of Information Act (FOIA) officer.

-   The URL of the agency’s primary website, and the name and title of the staff person who is most directly responsible for website management.

-   The title of the agency’s primary Facebook, Twitter, YouTube, and Instagram social media platforms (list as many as applicable).

-   From the agency’s website, name the section or page where you found the following: the next regular governing board meeting agenda, a feedback or “contact us” form, the current budget, and the most recent ACFR.

-   Identify three professional organizations the agency is a member of (i.e., Illinois Municipal League American Public Works Association, Northwest Municipal Conference) and who is the designated representative to each.