---
title: "Individual paper 2"
date: 2024-02-06
---

In a typewritten paper of 600-900 words, interview your immediate supervisor at the agency where you are either a full-time employee or intern. The paper must include answers and discussion on each of the following topics (one point per full response to each):

-   Ask the supervisor to discuss their education, previous positions within this agency, and their prior relevant employment.

-   Ask the supervisor to describe their work typical day, and interactions with their supervisor or to whom they report.

-   Ask them to describe their relationships with other departments, and other public agencies (schools, park district, library, etc.).

-   Ask the supervisor to conduct a mini-SWOT analysis of the agency, or the department or organization where you both work, identifying up to three issues for each SWOT (Strengths, Weaknesses, Opportunities, Threats) element, and the reason for each response.

-   Ask where they see themselves, and this agency, in ten years.

-   You may ask additional questions, or engage in more topics, as you wish.