---
title: "Research paper"
date: 2024-03-05
---

In a typewritten paper of between 3000-3600 total words (exceeding the word limit will result in deduction of points), excluding a cover page and reference list page(s), present the team’s collaborative policy research, to include:

-   A statement that defines the issue, its importance, the central controversies and options for solutions to resolve the issue. This section should be 600-900 words.

-   A review of relevant research that provides evidence to support the team’s arguments, including problem or issue definitions, elements of the issue, and the alternatives to be considered, both pro and con. This section will include references to literature the team will find as a part of its research, so be sure to use appropriate citations. If the team uses a personal interview as a part of the research, be sure to obtain permission from the interviewee prior to the interview, disclose the purpose of the interview, record the answers, and cite the interview as appropriate. This section should be from 1500 to 2100 words.

-   The concluding section of the paper will serve as the team’s preferred option for resolving or addressing the issue. Restate the policy issue, its relevance and importance to the agency, and the reasons for your recommendation based on the research within the paper. This section should be from 600 to 900 words.